# Generated by Django 3.2.3 on 2021-05-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('link', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('country', models.CharField(default='India', max_length=30)),
                ('region', models.CharField(default='South', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.BooleanField(null=True)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
